(function(e){function j(a,m){if(g[a])return g[a];var l=a.replace(d,"").replace(f,"");m&&b.forEach(function(b,a){l=l.replace(b,c[a])});return g[a]=l}function k(b,c,d){var f,e,k,b=j(b);e=a[b]||(a[b]={});if(k=e.exports)throw Error(b+" has already defined");e.id=b;k=e.exports={};var q=b,s=q.split(i);s.pop();c.forEach(function(b){var c,d,o,b=j(b,!0);if(0===b.indexOf(".")){c=b.split(i);for(d=s.slice();o=c.shift();)".."===o?d.pop():"."!==o&&d.push(o);c=d.join(i)}c&&b!==c&&(g[b]=c);if(!a[c||b])throw Error('require a undefined module "'+
(c||b)+'" in "'+q+'"');});f=function(b){return h(b)};"function"===typeof d?(e.executed=!1,e.factory=d,e.exports=function(){var b=this.factory;this.exports=b(f,this.exports,this)||this.exports;this.executed=!0;delete this.factory;return this.exports}):(e.executed=!0,e.exports=d)}function h(b){var b=j(b,!0),c=a[b];if(c&&c.exports)return c.executed?c.exports:c.exports();throw Error(b+" has not defined");}if(!e.define){var i="/",d=/^#/,f=/\.js$/i,a=e.modules||(e.modules={}),b=[],c=[],g={};e.define=k;
e.require=h}})(window,window.document);
define("#mix/core/0.3.0/base/reset-debug",[],function(){var e=Object.prototype.toString,j=Object.prototype.hasOwnProperty,k=Array.prototype.slice;Object.keys||(Object.keys=function(a){var b=[],c=0,g;for(g in a)j.call(a,g)&&(b[c++]=g);return b});Object.each||(Object.each=function(a,b,c){if(a!=null)if(j.call(a,"length"))Array.prototype.forEach.call(a,b,c);else if(typeof a==="object")for(var g in a)j.call(a,g)&&b.call(c,a[g],g,a)});Object.clone||(Object.clone=function(a,b){return Object.isTypeof(a,"array")?
b?arr.map(function(a){return Object.clone(a,b)}):a.slice():typeof a==="object"?Object.extend({},a,b):a});Object.extend||(Object.extend=function(a,b,c){var g=Array.make(arguments),a=g.shift(),c=g.pop();if(!Object.isTypeof(c,"boolean")){g.push(c);c=void 0}Object.each(g,function(b){Object.each(b,function(b,g){a[g]=c?Object.clone(b):b})});return a});if(!Object.isTypeof){var h=/^\[object\s\s*(\w\w*)\s*\]$/;Object.isTypeof=function(a,b){var c=e.call(a).toLowerCase();if(c=h.exec(c)){c=c[1];return b?c===
b.toLowerCase():c}}}!Array.make&&!Array.from&&(Array.from=Array.make=function(a){if(j.call(a,"length"))return k.call(a)});Array.equal||(Array.equal=function(a,b){if(a.length==b.length){for(var c=0;c<a.length;c++)if(a[c]!==b[c])return false;return true}return false});Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,g=0;g<c;g++)g in this&&a.call(b,this[g],g,this)});Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,g=Array(c),d=0;d<c;d++)d in
this&&(g[d]=a.call(b,this[d],d,this));return g});Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,g=[],d,f=0;f<c;f++){d=this[f];a.call(b,d,f,this)&&g.push(d)}return g});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length,g=b||0;if(!c||g>=c)return-1;for(g<0&&(g=g+c);g<length;g++)if(j.call(this,g)&&a===this[g])return g;return-1});if(!String.prototype.trim){var i=/^\s\s*/,d=/\s\s*$/;String.prototype.trim=function(){return this.replace(i,
"").replace(d,"")}}if(!Function.prototype.bind){var f=function(){};Function.prototype.bind=function(a){var b=this,c=Array.make(arguments),g;if(!Object.isTypeof(b,"function"))throw new TypeError;c=c.slice(1);return g=function(){var d=Array.make(arguments);if(!(this instanceof g))return b.apply(a,c.concat(d));f.prototype=b.prototype;var e=new f,d=b.apply(e,c.concat(d));return Object(d)===d?d:e}}}});
define("#mix/core/0.3.0/base/class-debug",[],function(e,j,k){function h(b){if(!(this instanceof h)&&Object.isTypeof(b,"function"))return f(b)}function i(){}function d(b){var a,g;for(a in b)g=b[a],h.Mutators.hasOwnProperty(a)?h.Mutators[a].call(this,g):this.prototype[a]=g}function f(b){b.extend=h.extend;b.implement=d;return b}h.create=function(b,a){function g(){b.apply(this,arguments);this.constructor===g&&this.initialize&&this.initialize.apply(this,arguments)}Object.isTypeof(b,"function")||(a=b,b=
null);a||(a={});b||(b=a.Extends||h);a.Extends=b;b!==h&&Object.extend(g,b);d.call(g,a);return f(g)};h.extend=function(b){b||(b={});b.Extends=this;return h.create(b)};h.Mutators={Extends:function(b){var c=this.prototype,g=a(b.prototype);Object.extend(g,c);g.constructor=this;this.prototype=g;this.superclass=b.prototype},Implements:function(b){Object.isTypeof(b,"array")||(b=[b]);for(var a=this.prototype,g,d=a.constructor;g=b.shift();)Object.extend(a,g.prototype||g);a.constructor=d},Statics:function(b){Object.extend(this,
b)}};if(Object.__proto__)var a=function(b){return{__proto__:b}};else i=function(){},a=function(b){i.prototype=b;return new i};k.exports=h});
define("#mix/core/0.3.0/base/message-debug",["mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug"],function(e,j,k){function h(a,b){var c,g,f;(g=b.match(d))&&"*"===g[1]?(c=[],f=RegExp("^(@[^\\:]+\\:)?"+b+"$"),Object.each(a,function(b,a){f.test(a)&&(c=c.concat(b))})):c=a[b];return c}e("mix/core/0.3.0/base/reset-debug");var i=/\s+/,d=/^\@([^:]+)\:/,f=0,e=e("mix/core/0.3.0/base/class-debug").create({initialize:function(a,b,c){this.__msgObj={name:a||"anonymous",id:b||f++,cache:{},defaultContext:c||
this}},on:function(a,b,c){var g=this.__msgObj.cache,f=this.__msgObj.defaultContext,e,l;if(!b)return this;a&&(e=a.match(d))?a=a.split(":")[1]:e=[""];for(a=a.split(i);l=a.shift();)l=e[0]+l,l=g[l]||(g[l]=[]),l.push(b,c||f);return this},off:function(a,b,c){var g=this.__msgObj.cache,f="",e,l;if(!a&&!b&&!c)return delete this.__msgObj.events,this;a&&(f=a.match(d))?a=a.split(":")[1].split(i):(a=a?a.split(i):Object.keys(g),f=[""]);for(;e=a.shift();)if(e=f[0]+e,l=g[e])if(!b&&!c)delete g[e];else for(e=l.length-
2;0<=e;e-=2)b&&l[e]!==b||c&&l[e+1]!==c||l.splice(e,2);return this},has:function(a,b,c){var a=h(this.__msgObj.cache,a),g;if(!a)return!1;if(!b&&!c)return!0;for(g=a.length-2;0<=g;g-=2)if(!(b&&a[g]!==b||c&&a[g+1]!==c))return!0;return!1},once:function(a,b,c){function g(){b.apply(this,arguments);d.off(a,g,c)}var d=this;d.on(a,g,c)},trigger:function(a){var b=this.__msgObj.cache,c=this.__msgObj.defaultContext,g,d,f,e,j,k=[],a=a.split(i);e=1;for(j=arguments.length;e<j;e++)k[e-1]=arguments[e];for(;g=a.shift();){this.log(g+
":("+k.join(",")+")");if(d=b.all)d=d.slice();if(f=h(b,g))f=f.slice();if(f){e=0;for(j=f.length;e<j;e+=2)f[e].apply(f[e+1]||c,k)}if(d){g=[g].concat(k);e=0;for(j=d.length;e<j;e+=2)d[e].apply(d[e+1]||c,g)}}return this},log:function(a){console.log("[("+this.__msgObj.id+")"+this.__msgObj.name+"]",{id:this.__msgObj.id,name:this.__msgObj.name,msg:a})}});e.SPLITER_REG=i;e.AT_REG=d;e.singleton=new e("global");k.exports=e});
define("#mix/core/0.3.0/base/util-debug",["mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug"],function(e,j,k){e("mix/core/0.3.0/base/reset-debug");var h={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","/":"&#x2F;"},i=/^[-+]?\d\d*\.?\d\d*/,d=/[&<>"'\/]/g,e=e("mix/core/0.3.0/base/class-debug").create({initialize:function(){},escape:function(e){return(""+e).replace(d,function(a){return h[a]})},str2val:function(d){if(null==d||void 0==d||NaN==d)return d;d+="";return"true"===
d||"false"===d?"true"===d?!0:!1:i.test(d)?parseFloat(d):d}});e.singleton=new e;k.exports=e});
define("#mix/core/0.3.0/url/router-debug",["mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug","mix/core/0.3.0/base/message-debug"],function(e,j,k){e("mix/core/0.3.0/base/reset-debug");var j=e("mix/core/0.3.0/base/class-debug"),h=e("mix/core/0.3.0/base/message-debug"),i=window,d=i.location,f=j.create({Implements:h,initialize:function(){h.prototype.initialize.call(this,"router");this._handlers=[];this._options={};this._changeHanlder=this._changeHanlder.bind(this)},_getHash:function(){return d.hash.slice(1)||
""},_setHash:function(a){d.hash=a},_resetHandler:function(){Object.each(this._handlers,function(a){a.matched=!1})},_changeHanlder:function(){this._resetHandler();this.match()},start:function(a){if(f.started)return!1;f.started=!0;i.addEventListener("hashchange",this._changeHanlder,!1);a=Object.extend(this._options,a||{});!1!==a.firstMatch&&this.match();return!0},stop:function(){if(!f.started)return!1;i.removeEventListener("hashchange",this._changeHanlder,!1);f.started=!1;this._options={};this._handlers=
[];this._fragment=null;return!0},match:function(){var a=this._handlers,b,c,d=!0;if(f.started){c=this._fragment=this._getHash();for(var e=0;e<a.length&&!(b=a[e],!b.matched&&b.route.test(c)&&(d=!1,b.matched=!0,b.callback(c),b.last));e++);d&&this.trigger("unmatched",c)}},add:function(a,b,c){this._handlers.push({route:a,callback:b,matched:!1,last:!!c})},remove:function(a,b){for(var c=this._handlers,d=0;d<c.length;d++){var e=c[d];if(e.route.source===a.source&&(!b||e.callback===b))return c.splice(d,1)}},
navigate:function(a){f.started&&(a||(a=""),this._fragment!==a&&this._setHash(a))}});f.started=!1;f.singleton=new f;k.exports=f});
define("#mix/core/0.3.0/url/navigate-debug",["mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug","mix/core/0.3.0/base/message-debug","mix/core/0.3.0/url/router-debug"],function(e,j,k){e("mix/core/0.3.0/base/reset-debug");var j=e("mix/core/0.3.0/base/class-debug"),h=e("mix/core/0.3.0/base/message-debug"),e=e("mix/core/0.3.0/url/router-debug"),i=/\:(\w\w*)/g,d=/\*(\w\w*)/g,f=/P\<(\w\w*?)\>/g,a=window.history,j=j.create({Implements:h,initialize:function(b){h.prototype.initialize.call(this,
"navigate");this._datas=this._move=null;this._routes={};this._states=[];this._stateIdx=0;this._stateLimit=b.stateLimit||100;this._router=b.useRouter},_convertParams:function(b){return b.replace(i,"(P<$1>[^\\/]*?)").replace(d,"(P<$1>.*?)")},_extractNames:function(b){var b=b.match(f),a={};b&&Object.each(b,function(b,d){a[b.replace(f,"$1")]=d});return a},_extractArgs:function(b){var a=b.split("&"),b={};Object.each(a,function(a){a&&(a=a.split("="),b[a[0]]=a[1])});return b},_parseRoute:function(b){b=b.replace(f,
"");return RegExp("^("+b+")(!.*?)?$")},_stateEquals:function(b,a){return!b||!a||b.name!==a.name||b.fragment!==a.fragment?!1:!0},_pushState:function(b,a,d,e){var f=this._states,i=this._stateIdx,j=this._stateLimit,h=f.length,k=this._move,q=this._transition,s=this._datas,t=f[i-1],u=f[i+1],b={name:b,fragment:a,params:d,args:e};null==k&&(q=!s&&this._stateEquals(t,b)?k="backward":k="forward");"backward"===k?0===i&&0<h?f.unshift(b):0<i&&(i--,b=t):"forward"===k&&(i===j-1?(f.shift(),f.push(b)):0===i&&0===
h?f.push(b):!s&&this._stateEquals(u,b)?(i++,b=u):(i++,f.splice(i),f.push(b)));b.move=k;b.transition=q;s&&(b.datas=s);this._datas=this._move=null;this._stateIdx=i;this.trigger(k,b);return b},getState:function(){return this._states[this._stateIdx]},getStateIndex:function(){return this._stateIdx},addRoute:function(b,a,d){var e=this,f,i;1===arguments.length&&(d=arguments[0],a=b=null);d||(d={});if(d["default"])e._router.on("unmatched",function(a){a=e._pushState(b,a);d.callback&&d.callback(a)});else b&&
a&&(a=e._convertParams(a),f=e._extractNames(a),i=e._parseRoute(a),e._routes[b]=i,e._router.add(i,function(a){var c=a.match(i).slice(2),j=e._extractArgs(c.pop()||""),h={};Object.each(f,function(a,b){h[b]=c[a]});a=e._pushState(b,a,h,j);d.callback&&d.callback(a)},d.last))},removeRoute:function(a){(a=this._routes[a])&&this._router.remove(a)},forward:function(b,c){var d=this._states[this._stateIdx]||{},e=[];this._transition=this._move="forward";c||(c={});if(b){if(c.datas||d.fragment!==b)c.args&&Object.each(c.args,
function(a,b){e.push(b+"="+a)}),c.datas&&(this._datas=Object.clone(c.datas)),"backward"===c.transition&&(this._transition="backward"),this._router.navigate(b+(e.length?"!"+e.join("&"):""))}else a.forward()},backward:function(b){0!==this._stateIdx&&(this._transition=this._move="backward",b||(b={}),"forward"===b.transition&&(this._transition="forward"),a.back())}});j.singleton=new j({useRouter:e.singleton});k.exports=j});
define("#mix/sln/0.3.0/modules/gesture-debug",["mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug"],function(e){function j(e,d,f){var a=document.createEvent("HTMLEvents");a.initEvent(e,!0,!0);d&&(f?Object.each(f,function(b){a[b]=d[b]}):Object.extend(a,d));return a}e("mix/core/0.3.0/base/reset-debug");var k=window.document,h="screenX screenY clientX clientY pageX pageY".split(" ");return e("mix/core/0.3.0/base/class-debug").create({initialize:function(e){this._el=e;this._myGestures=
{};this._lastTapTime=NaN;this._onStart=this._onStart.bind(this);this._onDoing=this._onDoing.bind(this);this._onEnd=this._onEnd.bind(this);this._onTap=this._onTap.bind(this)},getElement:function(){return that._el},enable:function(){var e=this._el;e.addEventListener("touchstart",this._onStart,!1);e.addEventListener("tap",this._onTap,!1)},disable:function(){var e=this._el;e.removeEventListener("touchstart",this._onStart,!1);e.removeEventListener("tap",this._onTap,!1)},_onStart:function(e){var d=this._el,
f=this._myGestures;0===Object.keys(f).length&&(k.body.addEventListener("touchmove",this._onDoing,!1),k.body.addEventListener("touchend",this._onEnd,!1));Object.each(e.changedTouches,function(a){var c={},e;for(e in a)c[e]=a[e];var i={startTouch:c,startTime:Date.now(),status:"tapping",pressingHandler:setTimeout(function(){if(i.status==="tapping"){i.status="pressing";var a=j("press",c);d.dispatchEvent(a)}clearTimeout(i.pressingHandler);i.pressingHandler=null},500)};f[a.identifier]=i});if(2==Object.keys(f).length){var a=
j("dualtouchstart");a.touches=JSON.parse(JSON.stringify(e.touches));d.dispatchEvent(a)}},_onDoing:function(e){var d=this._el,f=this._myGestures;Object.each(e.changedTouches,function(a){var b=f[a.identifier],c,e,g;if(b&&(c=a.clientX-b.startTouch.clientX,e=a.clientY-b.startTouch.clientY,g=Math.sqrt(Math.pow(c,2)+Math.pow(e,2)),"tapping"==b.status&&10<g&&(b.status="panning",g=j("panstart",a,h),d.dispatchEvent(g)),"panning"==b.status))g=j("pan",a,h),g.displacementX=c,g.displacementY=e,d.dispatchEvent(g)});
if(2==Object.keys(f).length){var a=[],b=[],c;Object.each(e.touchs,function(c){var d;if(d=f[c.identifier])a.push([d.startTouch.clientX,d.startTouch.clientY]),b.push([c.clientX,c.clientY])});var g=a[0][0],k=a[0][1],m=a[1][0],l=a[1][1],r=b[0][0],p=b[0][1],n=b[1][0],q=b[1][1];c=Math.atan2(q-p,n-r)-Math.atan2(l-k,m-g);m=Math.sqrt((Math.pow(q-p,2)+Math.pow(n-r,2))/(Math.pow(l-k,2)+Math.pow(m-g,2)));g=[r-m*g*Math.cos(c)+m*k*Math.sin(c),p-m*k*Math.cos(c)-m*g*Math.sin(c)];c={rotate:c,scale:m,translate:g,matrix:[[m*
Math.cos(c),-m*Math.sin(c),g[0]],[m*Math.sin(c),m*Math.cos(c),g[1]],[0,0,1]]};c=j("dualtouch",c);c.touches=JSON.parse(JSON.stringify(e.touches));d.dispatchEvent(c)}},_onEnd:function(e){var d=this._el,f=this._myGestures,a;2==Object.keys(f).length&&(a=j("dualtouchend"),a.touches=JSON.parse(JSON.stringify(e.touches)),d.dispatchEvent(a));for(var b=0;b<e.changedTouches.length;b++){var c=e.changedTouches[b],g=c.identifier,o=f[g];if(o){o.pressingHandler&&(clearTimeout(o.pressingHandler),o.pressingHandler=
null);"tapping"===o.status&&(a=j("tap",c,h),d.dispatchEvent(a));if("panning"===o.status){a=j("panend",c,h);d.dispatchEvent(a);var m=Date.now()-o.startTime;300>m&&(a=j("flick",c,h),a.duration=m,a.valocityX=(c.clientX-o.startTouch.clientX)/m,a.valocityY=(c.clientY-o.startTouch.clientY)/m,a.displacementX=c.clientX-o.startTouch.clientX,a.displacementY=c.clientY-o.startTouch.clientY,d.dispatchEvent(a))}"pressing"===o.status&&(a=j("pressend",c,h),d.dispatchEvent(a));delete f[g]}}0==Object.keys(f).length&&
(k.body.removeEventListener("touchend",this._onEnd),k.body.removeEventListener("touchmove",this._onDoing))},_onTap:function(e){var d=this._el,f=this._lastTapTime;if(500>Date.now()-f){var a=document.createEvent("HTMLEvents");a.initEvent("doubletap",!0,!0);Object.each(h,function(b){a[b]=e[b]});d.dispatchEvent(a)}this._lastTapTime=Date.now()}})});
define("#mix/sln/0.3.0/modules/transform-debug",[],function(e,j){function k(b,c){b+="";c+="";0>b.indexOf("%")&&"0"!==b&&(b+="px");0>c.indexOf("%")&&"0"!==c&&(c+="px");return f&&a?"translate3d("+b+", "+c+", 0)":"translate("+b+", "+c+")"}var h=/^matrix3d\(\d+, \d+, \d+, \d+, \d+, \d+, \d+, \d+, \d+, \d+, \d+, \d+, ([\d-]+), ([-\d]+), [\d-]+, \d+\)/,i=/^matrix\(\d+, \d+, \d+, \d+, ([-\d]+), ([-\d]+)\)$/,d=navigator.appVersion;/android/gi.test(d);var f=/iphone|ipad/gi.test(d),a="WebKitCSSMatrix"in window&&
"m11"in new WebKitCSSMatrix;j.getY=function(a){var c,a=getComputedStyle(a).webkitTransform;return"none"!==a&&((c=a.match(h))||(c=a.match(i)))?parseInt(c[2])||0:0};j.getX=function(a){var c,a=getComputedStyle(a).webkitTransform;return"none"!==a&&((c=a.match(h))||(c=a.match(i)))?parseInt(c[1])||0:0};j.getTranslate=k;j.getBezier=function(a,c){return[[(a/3+(a+c)/3-a)/(c-a),(a*a/3+2*a*c/3-a*a)/(c*c-a*a)],[(c/3+(a+c)/3-a)/(c-a),(c*c/3+2*a*c/3-a*a)/(c*c-a*a)]]};j.start=function(a,c,d,e,f,i,j){var h=function(c){n||
c&&(c.srcElement!==a||"-webkit-transform"!==c.propertyName)||(n=!0,a.style.webkitTransition="none",a.removeEventListener("webkitTransitionEnd",h,!1),j&&setTimeout(j,50))},n=!1;a.addEventListener("webkitTransitionEnd",h,!1);a.style.webkitTransition=["-webkit-transform",c,d,e].join(" ");a.style.webkitTransform=k(f,i)}});
define("#mix/sln/0.3.0/modules/scroll-debug",["./gesture-debug","./transform-debug","mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug"],function(e){function j(a){var b=a.parentNode,c=getComputedStyle(b),a=0-a.scrollHeight+b.offsetHeight-parseInt(c.paddingTop)-parseInt(c.paddingBottom);0<a&&(a=0);return a}e("mix/core/0.3.0/base/reset-debug");var k=window.document,h=e("mix/core/0.3.0/base/class-debug"),i=e("./gesture-debug"),d=e("./transform-debug"),f=!1;return h.create({initialize:function(a){this._wrap=
a;this._scroller=a.children[0];this._gesture=new i(this._scroller);this._scrollEndHandler=this._scrollHeight=this._currentY=this._originalY=null;this._refreshed=this._scrollEndCancel=!1;this._preventBodyTouch=this._preventBodyTouch.bind(this);this._onTouchStart=this._onTouchStart.bind(this);this._onPanStart=this._onPanStart.bind(this);this._onPan=this._onPan.bind(this);this._onPanEnd=this._onPanEnd.bind(this);this._onFlick=this._onFlick.bind(this);this._onScrollEnd=this._onScrollEnd.bind(this)},enable:function(){var a=
this._scroller;this._gesture.enable();a.addEventListener("touchstart",this._onTouchStart,!1);a.addEventListener("panstart",this._onPanStart,!1);a.addEventListener("pan",this._onPan,!1);a.addEventListener("panend",this._onPanEnd,!1);a.addEventListener("flick",this._onFlick,!1);f||(f=!0,k.body.addEventListener("touchmove",this._preventBodyTouch,!1))},disable:function(){var a=this._scroller;this._gesture.disable();a.removeEventListener("touchstart",this._onTouchStart,!1);a.removeEventListener("panstart",
this._onPanStart,!1);a.removeEventListener("pan",this._onPan,!1);a.removeEventListener("panend",this._onPanEnd,!1);a.removeEventListener("flick",this._onFlick,!1);f&&(f=!1,k.body.removeEventListener("touchmove",this._preventBodyTouch,!1))},refresh:function(){this._refreshed=!0},getHeight:function(){return this._scroller.offsetHeight},getTop:function(){return-d.getY(this._scroller)},to:function(a){var b=this._scroller,c=j(b),a=-a;a<c?a=c:0<a&&(a=0);b.style.webkitTransform=d.getTranslate(0,a);this._onScrollEnd()},
_preventBodyTouch:function(a){a.preventDefault();return!1},_onTouchStart:function(){var a=this._scroller;a.style.webkitTransition="none";a.style.webkitTransform=getComputedStyle(a).webkitTransform;this._refreshed&&(this._refreshed=!1,this._scrollHeight=a.offsetHeight,a.style.height="auto",a.style.height=this._scrollHeight+"px")},_onPanStart:function(){this._originalY=d.getY(this._scroller)},_onPan:function(a){var b=this._scroller,c=j(b),a=this._currentY=this._originalY+a.displacementY;b.style.webkitTransform=
0<a?d.getTranslate(0,a/2):a<c?d.getTranslate(0,(c-a)/2+a):d.getTranslate(0,a)},_onPanEnd:function(){var a=this._scroller,b=this._currentY,c=j(a),e=null;0<b&&(e=0);b<c&&(e=c);null!=e?d.start(a,"0.4s","ease-out","0s",0,e,this._onScrollEnd):this._onScrollEnd()},_onFlick:function(a){var b=this,c=b._scroller,e=b._currentY,f=j(c);b._scrollEndCancel=!0;if(!(e<f||0<e)){var i=d.getY(c),h=a.valocityY;1.5<h&&(h=1.5);-1.5>h&&(h=-1.5);var k=0.0015*(h/Math.abs(h)),p=h/k,n=i+p*h/2;if(0<n||n<f){var a=0<n?1:-1,q=
0<n?0:f,n=(n-q)/2+q,p=(a*Math.sqrt(2*k*(n-i)+h*h)-h)/k;v=h-k*p;d.start(c,p.toFixed(0)+"ms","cubic-bezier("+d.getBezier(-h/k,-h/k+p)+")","0s",0,n.toFixed(0),function(){h=v;i=n;k=0.0045*(h/Math.abs(h));p=-h/k;n=q;d.start(c,(0-p).toFixed(0)+"ms","cubic-bezier("+d.getBezier(-p,0)+")","0s",0,n.toFixed(0),b._onScrollEnd)})}else d.start(c,p.toFixed(0)+"ms","cubic-bezier("+d.getBezier(-p,0)+")","0s",0,n.toFixed(0),b._onScrollEnd)}},_onScrollEnd:function(){var a=this;a._scrollEndCancel=!1;setTimeout(function(){a._scrollEndCancel||
a._scrollEndHandler&&a._scrollEndHandler()},10)}})});
define("#mix/sln/0.3.0/modules/component-debug","./scroll-debug ./gesture-debug ./transform-debug mix/core/0.3.0/base/reset-debug mix/core/0.3.0/base/class-debug mix/core/0.3.0/base/message-debug mix/core/0.3.0/url/navigate-debug".split(" "),function(e){e("mix/core/0.3.0/base/reset-debug");var j=e("mix/core/0.3.0/base/class-debug"),k=e("mix/core/0.3.0/base/message-debug");e("mix/core/0.3.0/url/navigate-debug");var h=e("./scroll-debug"),i=e("./transform-debug"),d={},f=function(a,b){a.fn||(a.fn={});
Object.extend(a.fn,b)};return new (j.create({Implements:k,initialize:function(){k.prototype.initialize.call(this,"component")},get:function(a){return d[a]},initViewport:function(a){d.viewport=a;a.setAttribute("id","viewport-"+Date.now())},initTitlebar:function(a){d.viewport.className=d.viewport.className+" enableTitlebar";d.titlebar=a;f(a,{change:function(b,c){function d(){e.className="";e.removeEventListener("webkitTransitionEnd",d)}var e=a.querySelector("ul");e.querySelector("li:first-child").innerHTML=
b;e.className=c;setTimeout(function(){e.className=e.className+" transition";e.addEventListener("webkitTransitionEnd",d,false)},1)}})},initBtn:function(a,b){d[a]=b;var c=this;f(b,{setText:function(a){b.innerText=a},show:function(){b.style.visibility=""},hide:function(){b.style.visibility="hidden"}});b.addEventListener("click",function(b){c.trigger(a+"Click");b.preventDefault();return false});return b},initBackBtn:function(a){this.initBtn("backBtn",a)},initFuncBtn:function(a){this.initBtn("funcBtn",
a)},initContent:function(a){d.content=a;var b=a.querySelector("div > .active"),c=a.querySelector("div > .inactive");f(a,{getActive:function(){return b},getInactive:function(){return c},switchActive:function(){swap=c;c=b;b=swap},setClass:function(){c.className="inactive";b.className="active"}})},getActiveContent:function(){return d.content.fn.getActive()},initScroll:function(a){d.scroll=a;var b=this,c=new h(a);d.viewport.className=d.viewport.className+" enableScroll";a.className=a.className+" scroll";
c._scrollEndHandler=function(){b.trigger("scrollEnd")};c.enable();f(a,{refresh:function(){c.refresh()},getScrollHeight:function(){return c.getHeight()},getScrollTop:function(){return c.getTop()},scrollTo:function(a){c.to(a)}})},initTransition:function(a){function b(b){var d=a.querySelector("div"),f;e.fn.switchActive();e.fn.getActive().innerHTML="";f=i.getY(d);i.start(d,"0.4s","ease",0,(b==="forward"?"-":"")+"33.33%",f,function(){e.fn.setClass();f=i.getY(d);d.style.webkitTransform=i.getTranslate(0,
f);c.trigger(b+"TransitionEnd")})}d.transition=a;var c=this,e=d.content;d.viewport.className=d.viewport.className+" enableTransition";a.className=a.className+" transition";f(a,{forward:function(){b("forward")},backward:function(){b("backward")}})}}))});
define("#mix/sln/0.3.0/modules/page-debug",["mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug","mix/core/0.3.0/base/message-debug"],function(e){e("mix/core/0.3.0/base/reset-debug");var j=window,k=e("mix/core/0.3.0/base/class-debug"),h=e("mix/core/0.3.0/base/message-debug"),i={UNKOWN:0,UNLOADED:0,READY:1,COMPILED:2},d={},f=k.create({Implements:h,initialize:function(){h.prototype.initialize.call(this,"app."+this.name);this.status=i.UNKOWN;this.ready=this.ready.bind(this);this.unload=
this.unload.bind(this);this.on("ready",this.ready);this.on("unloaded",this.unload)},getTitle:function(){return this.title},loadTemplate:function(a,b){1===arguments.length&&(b=arguments[0],a=this.template);a&&app.loadFile(a,b)},compileTemplate:function(a,b){var c;if(c=j.Mustache)this.compiledTemplate=c.compile(a),b(this.compiledTemplate)},renderTemplate:function(a,b){var c=this.compiledTemplate,c=c(a);b(c)},fill:function(a,b){function c(){d.renderTemplate(a,function(a){d.trigger("rendered",a);b&&b()})}
var d=this;if(d.compiledTemplate)c();else d.once("compiled",c)},ready:function(){},unload:function(){}});f.STATUS=i;f.fn={};f.define=function(a){a=f.extend(a);a.implement(f.fn);a=new a;return d[a.name]=a};f.get=function(a){return d[a]};f.each=function(a){Object.each(d,a)};return f});
define("#mix/sln/0.3.0/modules/navigation-debug",["./page-debug","mix/core/0.3.0/base/reset-debug","mix/core/0.3.0/base/class-debug","mix/core/0.3.0/url/navigate-debug","mix/core/0.3.0/base/message-debug"],function(e){e("mix/core/0.3.0/base/reset-debug");var j=e("mix/core/0.3.0/base/class-debug"),k=e("mix/core/0.3.0/url/navigate-debug").singleton,h=e("./page-debug"),i=h.STATUS,e=j.create({initialize:function(d){var e=d.name.split(".");this.appName=e[0];this.routeName=e[1];this.state=d},ready:function(){var d=
h.get(this.appName);d.status<i.READY&&(d.status=i.READY,d.trigger("ready"))},compile:function(){function d(){e.status<i.COMPILED&&(e.status=i.COMPILED,e.trigger("compiled"))}var e=h.get(this.appName);e.compiledTemplate?d():e.loadTemplate(function(a){e.compileTemplate(a,function(){d()})})},unload:function(){var d=h.get(this.appName);d.status>i.UNLOADED&&(d.status=i.UNLOADED,d.trigger("unloaded"))}});Object.extend(e,{_cur:null,getParameter:function(d){return this._cur.state.params[d]},getArgument:function(d){return this._cur.state.args[d]},
getData:function(d){return this._cur.state.datas[d]},push:function(d,e){k.forward(d,e)},pop:function(){k.backward()}});return e});
define("#mix/sln/0.3.0/app-debug","./modules/page-debug ./modules/component-debug ./modules/scroll-debug ./modules/gesture-debug ./modules/transform-debug ./modules/navigation-debug mix/core/0.3.0/base/reset-debug mix/core/0.3.0/base/class-debug mix/core/0.3.0/url/router-debug mix/core/0.3.0/url/navigate-debug mix/core/0.3.0/base/message-debug mix/sln/0.3.0/app-debug".split(" "),function(e){e("mix/core/0.3.0/base/reset-debug");var j=window;e("mix/core/0.3.0/base/class-debug");var k=e("mix/core/0.3.0/url/router-debug").singleton,
h=e("mix/core/0.3.0/url/navigate-debug").singleton,i=e("./modules/page-debug"),d=e("./modules/component-debug"),f=e("./modules/navigation-debug");app={};Object.extend(app,{config:{viewport:null,theme:"iOS",routePrefix:0,routePrefixSep:"/",enableTitlebar:false,enableScroll:false,enableTransition:false,enableToolbar:false},page:i,component:d,navigation:f,plugin:{},loadFile:function(a,b){var c=new j.XMLHttpRequest;c.onreadystatechange=function(){c.readyState===4&&(c.status>=200&&c.status<300||c.status===
304)&&b(c.responseText)};c.open("GET",a,true);c.send()},start:function(){var a=app.config.viewport,b=a.querySelector("header.titlebar"),c=b.querySelector("button.back"),e=b.querySelector("button.func");content=a.querySelector("section.content");toolbar=a.querySelector("footer.toolbar");d.initViewport(a);if(app.config.enableTitlebar){d.initTitlebar(b);d.initBackBtn(c);d.initFuncBtn(e)}d.initContent(content);app.config.enableScroll&&d.initScroll(content);app.config.enableTransition&&d.initTransition(content);
app.config.enableToolbar&&d.initToolbar();var j=d.get("titlebar"),m=d.get("backBtn"),l=d.get("funcBtn"),r=null,p=d.get("content"),n=d.get("transition");d.on("backBtnClick",function(){h.backward()});d.on("funcBtnClick",function(a){r&&r(a)});h.on("forward backward",function(a){a=new f(a);if(app.config.enableTransition)n.fn[a.state.transition]();else{p.fn.switchActive();p.fn.setClass()}app.navigation._cur&&app.navigation._cur.unload();app.navigation._cur=a;a.ready();a.compile();if(app.config.enableTitlebar){var b=
i.get(a.appName).buttons;m.fn.hide();l.fn.hide();b&&Object.each(b,function(a){switch(a.type){case "back":m.fn.setText(a.text);h.getStateIndex()>=1&&m.fn.show();break;case "func":l.fn.setText(a.text);r=a.handler;l.fn.show()}});b=a.state.transition;a=i.get(a.appName).getTitle();j.fn.change(a,b)}});i.each(function(a){var b=a.name,c=a.route;c?Object.isTypeof(c,"string")&&(c={name:"anonymous",text:c}):c={name:"default","default":true};h.addRoute(b+"."+c.name,c.text,c);a.on("rendered",function(a){var b=
d.get("scroll"),c=d.getActiveContent();c&&(c.innerHTML=a);b&&b.fn.refresh()})});app.plugin.init&&app.plugin.init();k.start()}});j.app=app});require("mix/sln/0.3.0/app-debug");
