(function(r,k){"object"===typeof exports&&exports?module.exports=k:"function"===typeof define&&define.amd?define(k):r.Mustache=k})(this,function(){function r(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function k(a){this.tail=this.string=a;this.pos=0}function i(a,b){this.view=a;this.parent=b;this._cache={}}function l(){this.clearCache()}function p(a,b,c,f){for(var d="",g,e,k=0,i=a.length;k<i;++k)switch(g=a[k],e=g[1],g[0]){case "#":e=c.lookup(e);if("object"===typeof e)if(t(e))for(var m=
0,h=e.length;m<h;++m)d+=p(g[4],b,c.push(e[m]),f);else e&&(d+=p(g[4],b,c.push(e),f));else"function"===typeof e?(g=null==f?null:f.slice(g[3],g[5]),e=e.call(c.view,g,function(a){return b.render(a,c)}),null!=e&&(d+=e)):e&&(d+=p(g[4],b,c,f));break;case "^":e=c.lookup(e);if(!e||t(e)&&0===e.length)d+=p(g[4],b,c,f);break;case ">":e=b.getPartial(e);"function"===typeof e&&(d+=e(c));break;case "&":e=c.lookup(e);null!=e&&(d+=e);break;case "name":e=c.lookup(e);null!=e&&(d+=j.escape(e));break;case "text":d+=e}return d}
function u(a){return[RegExp(r(a[0])+"\\s*"),RegExp("\\s*"+r(a[1]))]}var j={name:"mustache.js",version:"0.7.2",tags:["{{","}}"]};j.Scanner=k;j.Context=i;j.Writer=l;var x=/\s*/,v=/\s+/,y=/\S/,w=/\s*=/,z=/\s*\}/,A=/#|\^|\/|>|\{|&|=|!/,B=RegExp.prototype.test,C=Object.prototype.toString,t=Array.isArray||function(a){return"[object Array]"===C.call(a)},D={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"};j.escape=function(a){return String(a).replace(/[&<>"'\/]/g,function(a){return D[a]})};
k.prototype.eos=function(){return""===this.tail};k.prototype.scan=function(a){return(a=this.tail.match(a))&&0===a.index?(this.tail=this.tail.substring(a[0].length),this.pos+=a[0].length,a[0]):""};k.prototype.scanUntil=function(a){var b=this.tail.search(a);switch(b){case -1:a=this.tail;this.pos+=this.tail.length;this.tail="";break;case 0:a="";break;default:a=this.tail.substring(0,b),this.tail=this.tail.substring(b),this.pos+=b}return a};i.make=function(a){return a instanceof i?a:new i(a)};i.prototype.push=
function(a){return new i(a,this)};i.prototype.lookup=function(a){var b=this._cache[a];if(!b){if("."==a)b=this.view;else for(var c=this;c;){if(0<a.indexOf("."))for(var b=c.view,f=a.split("."),d=0;b&&d<f.length;)b=b[f[d++]];else b=c.view[a];if(null!=b)break;c=c.parent}this._cache[a]=b}"function"===typeof b&&(b=b.call(this.view));return b};l.prototype.clearCache=function(){this._cache={};this._partialCache={}};l.prototype.compile=function(a,b){var c=this._cache[a];c||(c=j.parse(a,b),c=this._cache[a]=
this.compileTokens(c,a));return c};l.prototype.compilePartial=function(a,b,c){b=this.compile(b,c);return this._partialCache[a]=b};l.prototype.getPartial=function(a){!(a in this._partialCache)&&this._loadPartial&&this.compilePartial(a,this._loadPartial(a));return this._partialCache[a]};l.prototype.compileTokens=function(a,b){var c=this;return function(f,d){if(d)if("function"===typeof d)c._loadPartial=d;else for(var g in d)c.compilePartial(g,d[g]);return p(a,c,i.make(f),b)}};l.prototype.render=function(a,
b,c){return this.compile(a)(b,c)};j.parse=function(a,b){a=a||"";b=b||j.tags;"string"===typeof b&&(b=b.split(v));if(2!==b.length)throw Error("Invalid tags: "+b.join(", "));for(var c=u(b),f=new k(a),d=[],g=[],e=[],i=!1,l=!1,m,h,n,q;!f.eos();){m=f.pos;if(n=f.scanUntil(c[0])){q=0;for(var p=n.length;q<p;++q)if(h=n.charAt(q),B.call(y,h)?l=!0:e.push(g.length),g.push(["text",h,m,m+1]),m+=1,"\n"==h){if(i&&!l)for(;e.length;)delete g[e.pop()];else e=[];l=i=!1}}if(!f.scan(c[0]))break;i=!0;h=f.scan(A)||"name";
f.scan(x);"="===h?(n=f.scanUntil(w),f.scan(w),f.scanUntil(c[1])):"{"===h?(n=f.scanUntil(RegExp("\\s*"+r("}"+b[1]))),f.scan(z),f.scanUntil(c[1]),h="&"):n=f.scanUntil(c[1]);if(!f.scan(c[1]))throw Error("Unclosed tag at "+f.pos);q=[h,n,m,f.pos];g.push(q);if("#"===h||"^"===h)d.push(q);else if("/"===h){if(0===d.length)throw Error('Unopened section "'+n+'" at '+m);h=d.pop();if(h[1]!==n)throw Error('Unclosed section "'+h[1]+'" at '+m);}else if("name"===h||"{"===h||"&"===h)l=!0;else if("="===h){b=n.split(v);
if(2!==b.length)throw Error("Invalid tags at "+m+": "+b.join(", "));c=u(b)}}if(h=d.pop())throw Error('Unclosed section "'+h[1]+'" at '+f.pos);for(var c=g,f=[],o,g=0,e=c.length;g<e;++g)if(d=c[g])"text"===d[0]&&o&&"text"===o[0]?(o[1]+=d[1],o[3]=d[3]):(o=d,f.push(d));o=f;f=c=[];d=[];e=0;for(i=o.length;e<i;++e)switch(g=o[e],g[0]){case "#":case "^":d.push(g);f.push(g);f=g[4]=[];break;case "/":d.pop()[5]=g[2];f=0<d.length?d[d.length-1][4]:c;break;default:f.push(g)}return c};var s=new l;j.clearCache=function(){return s.clearCache()};
j.compile=function(a,b){return s.compile(a,b)};j.compilePartial=function(a,b,c){return s.compilePartial(a,b,c)};j.compileTokens=function(a,b){return s.compileTokens(a,b)};j.render=function(a,b,c){return s.render(a,b,c)};j.to_html=function(a,b,c,f){a=j.render(a,b,c);if("function"===typeof f)f(a);else return a};return j}());
